spring:
  application:
    name: readservice
  cloud:
    function:
      definition: readMessageFromQueue
    stream:
      bindings:
        readMessageFromQueue-in-0:
          destination: myQueue
          group: myGroup
          consumer:
            max-attempts: 1
          binder: rabbit_mq
      rabbit:
        bindings:
          readMessageFromQueue-in-0:
            consumer:
              auto-bind-dlq: true

      binders:
        rabbit_mq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /